FROM node:20-alpine3.19

WORKDIR /app

RUN npm i -g pnpm

# Copy the package.json and pnpm-lock.yaml files to the working directory
COPY package.json pnpm-lock.yaml ./

# Install the project dependencies using pnpm
RUN pnpm install

# Copy the entire project directory to the working directory
COPY . .

EXPOSE 3000
# Set the command to start the development server using pnpm
CMD ["pnpm", "dev"]