import Header from '@/components/header';
import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import './globals.css';

const fontSans = FontSans({
    subsets: ['latin'],
    variable: '--font-sans',
});

export const metadata: Metadata = {
    title: 'Next Template',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt" suppressHydrationWarning>
            <head />
            <body
                className={cn(
                    'min-h-screen bg-gradient-to-b from-gray-50 to-gray-100 text-gray-900',
                    fontSans.variable,
                )}
            >
                <Header />
                <main className="flex flex-col items-center">{children}</main>
            </body>
        </html>
    );
}
