name: Check Pull Request Frontend
on:
    workflow_dispatch:
    pull_request:
        branches: [main, master, develop]
jobs:
    e2e-tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install pnpm ${{ vars.PNPM_VERSION }}
              uses: pnpm/action-setup@v4
              with:
                  version: ${{ vars.PNPM_VERSION }}

            - name: Use Node.js ${{ vars.NODE_VERSION }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ vars.NODE_VERSION }}
                  cache: 'pnpm'

            - name: Install project dependencies
              run: pnpm install

            - name: Check format of files
              run: pnpm format:check

            - name: Lint project
              run: pnpm lint

            - name: Validate Typescript
              run: pnpm ts:check
